version: 2
jobs:
  build:
    docker:
      - image: fedora:29
    working_directory: ~/workdir
    steps:
      - run:
          name: Install deps
          command: |
            dnf update -y > /dev/null
            dnf install -y git openssh-clients \
              gcc vala vala-devel valadoc gobject-introspection-devel 'pkgconfig(python3)' \
              'pkgconfig(gtk+-3.0)' sqlite-devel python3-pyparsing \
              wget tar xz git autoconf-archive \
              make autoconf automake glib2-devel graphviz-devel flex bison libxslt
            dnf clean all > /dev/null
      - run:
          name: Download Vala
          command: |
            git clone https://gitlab.gnome.org/GNOME/vala.git
      - run:
          name: Build Vala
          working_directory: ~/workdir/vala
          command: |
            ./autogen.sh --prefix=/usr
            make all
            dnf remove -y vala valadoc
            make install
      - run:
          name: Download Gee
          command: |
            git clone https://gitlab.gnome.org/GNOME/libgee.git
      - run:
          name: Build Gee
          working_directory: ~/workdir/libgee
          command: |
            ./autogen.sh --prefix=/usr --enable-introspection=no --disable-static --enable-gtk-doc=no
            make all
            make install
      - run:
          name: Install Valalint
          command: |
            git clone https://github.com/tiliado/valalint.git
            cd valalint
            make all
            make install
            cd ..
            rm -rf valalint
      - checkout:
          path: ~/workdir/diorite
      - run:
          name: Build and run tests
          working_directory: ~/workdir/diorite
          command: |
            ./waf configure build install
            /sbin/ldconfig
            LD_LIBRARY_PATH=./build ./build/run-dioritetests
